PILOT=15
FINAL=40
EXC="2.3"
SIMS=200
MODALITY='sim'
ADAPTIVE='predictive'
MODEL='CS'

. ./config.sh

export OUTDIR=$(echo $RESDIR\SIM_$ADAPTIVE\_$PILOT\_$EXC\_$MODEL)

python $SCRIPTDIR/aggregate_estimation.py $PILOT $FINAL $SIMS $MODALITY $ADAPTIVE $EXC $MODEL
